/*
 * Copyright 2015 Andrej Halaj.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.perfcake.pc4nb.wizards;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

public final class AddReporterVisualPanel1 extends JPanel {
    
    public AddReporterVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Add Reporter";
    }

    public JComboBox getReporterSelection() {
        return reporterSelection;
    }

    public JButton getAddPropertyButton() {
        return addPropertyButton;
    }

    public JButton getDeletePropertyButton() {
        return deletePropertyButton;
    }

    public JScrollPane getjScrollPane1() {
        return propertiesListScrollPane;
    }

    public JLabel getPropertiesLabel() {
        return propertiesLabel;
    }

    public JList getPropertiesList() {
        return propertiesList;
    }

    public JScrollPane getPropertiesListScrollPane() {
        return propertiesListScrollPane;
    }

    public JLabel getReporterTypeLabel() {
        return reporterTypeLabel;
    }
    
    public void addProperty(String name, String value) {
        propertiesListModel.insertElementAt(name + " : " + value, propertiesListModel.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reporterSelection = new javax.swing.JComboBox();
        reporterTypeLabel = new javax.swing.JLabel();
        propertiesLabel = new javax.swing.JLabel();
        propertiesListScrollPane = new javax.swing.JScrollPane();
        propertiesList = new javax.swing.JList();
        addPropertyButton = new javax.swing.JButton();
        deletePropertyButton = new javax.swing.JButton();
        destinationsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        destinationsList = new javax.swing.JList();
        addDestinationButton = new javax.swing.JButton();
        deleteDestinationButton = new javax.swing.JButton();
        editDestinationButton = new javax.swing.JButton();

        reporterSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MemoryUsageReporter", "Item 2", "Item 3", "Item 4" }));
        reporterSelection.setName("reporterSelection"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(reporterTypeLabel, org.openide.util.NbBundle.getMessage(AddReporterVisualPanel1.class, "AddReporterVisualPanel1.reporterTypeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(propertiesLabel, org.openide.util.NbBundle.getMessage(AddReporterVisualPanel1.class, "AddReporterVisualPanel1.propertiesLabel.text")); // NOI18N

        propertiesListModel = new DefaultListModel();
        propertiesList.setModel(propertiesListModel);
        propertiesList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        propertiesList.setVisibleRowCount(30000);
        propertiesListScrollPane.setViewportView(propertiesList);

        org.openide.awt.Mnemonics.setLocalizedText(addPropertyButton, org.openide.util.NbBundle.getMessage(AddReporterVisualPanel1.class, "AddReporterVisualPanel1.addPropertyButton.text")); // NOI18N
        addPropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPropertyButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(deletePropertyButton, org.openide.util.NbBundle.getMessage(AddReporterVisualPanel1.class, "AddReporterVisualPanel1.deletePropertyButton.text")); // NOI18N
        deletePropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePropertyButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(destinationsLabel, org.openide.util.NbBundle.getMessage(AddReporterVisualPanel1.class, "AddReporterVisualPanel1.destinationsLabel.text")); // NOI18N

        destinationsListModel = new DefaultListModel();
        destinationsList.setModel(destinationsListModel);
        jScrollPane1.setViewportView(destinationsList);

        org.openide.awt.Mnemonics.setLocalizedText(addDestinationButton, org.openide.util.NbBundle.getMessage(AddReporterVisualPanel1.class, "AddReporterVisualPanel1.addDestinationButton.text")); // NOI18N
        addDestinationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDestinationButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(deleteDestinationButton, org.openide.util.NbBundle.getMessage(AddReporterVisualPanel1.class, "AddReporterVisualPanel1.deleteDestinationButton.text")); // NOI18N
        deleteDestinationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDestinationButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(editDestinationButton, org.openide.util.NbBundle.getMessage(AddReporterVisualPanel1.class, "AddReporterVisualPanel1.editDestinationButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDestinationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteDestinationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editDestinationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(destinationsLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(propertiesListScrollPane)
                            .addComponent(propertiesLabel)
                            .addComponent(reporterTypeLabel)
                            .addComponent(reporterSelection, 0, 368, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addPropertyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletePropertyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(reporterTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reporterSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(propertiesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertiesListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPropertyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletePropertyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(destinationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addDestinationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editDestinationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteDestinationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPropertyButtonActionPerformed
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        JFrame frame = new JFrame();
        frame.setLocationRelativeTo(null);
        AddPropertyDialog dialog = new AddPropertyDialog(frame, true);
        dialog.setLocationRelativeTo(null);
        frame.pack();
        
        dialog.setVisible(true);
        
        if(!dialog.isNameEmptyOrNull() && !dialog.isValueEmptyOrNull()) {
            this.addProperty(dialog.getPropertyNameTextField().getText(), dialog.getPropertyValueTextField().getText());
        }
    }//GEN-LAST:event_addPropertyButtonActionPerformed

    private void deletePropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePropertyButtonActionPerformed
        if (propertiesList.getSelectedIndices().length > 0) {
            int[] elementsToRemove = propertiesList.getSelectedIndices();
            
            for (int i = elementsToRemove.length - 1; i >= 0; i--) {
                propertiesListModel.removeElementAt(elementsToRemove[i]);
            }
        }
    }//GEN-LAST:event_deletePropertyButtonActionPerformed

    private void addDestinationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDestinationButtonActionPerformed
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        JFrame frame = new JFrame();
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_addDestinationButtonActionPerformed

    private void deleteDestinationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDestinationButtonActionPerformed
        if (destinationsList.getSelectedIndices().length > 0) {
            int[] elementsToRemove = destinationsList.getSelectedIndices();
            
            for (int i = elementsToRemove.length - 1; i >= 0; i--) {
                destinationsListModel.removeElementAt(elementsToRemove[i]);
            }
        }
    }//GEN-LAST:event_deleteDestinationButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDestinationButton;
    private javax.swing.JButton addPropertyButton;
    private javax.swing.JButton deleteDestinationButton;
    private javax.swing.JButton deletePropertyButton;
    private javax.swing.JLabel destinationsLabel;
    private javax.swing.JList destinationsList;
    private javax.swing.DefaultListModel destinationsListModel;
    private javax.swing.JButton editDestinationButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel propertiesLabel;
    private javax.swing.JList propertiesList;
    private javax.swing.DefaultListModel propertiesListModel;
    private javax.swing.JScrollPane propertiesListScrollPane;
    private javax.swing.JComboBox reporterSelection;
    private javax.swing.JLabel reporterTypeLabel;
    // End of variables declaration//GEN-END:variables
}
