/*
 * Copyright 2015 Andrej Halaj.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.perfcake.pc4nb.wizards;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

public final class AddValidatorVisualPanel1 extends JPanel {
    
    public AddValidatorVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Add Validator";
    }

    public JComboBox getValidatorSelection() {
        return validatorSelection;
    }

    public JButton getAddPropertyButton() {
        return addPropertyButton;
    }

    public JButton getDeletePropertyButton() {
        return deletePropertyButton;
    }

    public JScrollPane getjScrollPane1() {
        return propertiesListScrollPane;
    }

    public JLabel getPropertiesLabel() {
        return propertiesLabel;
    }

    public JList getPropertiesList() {
        return propertiesList;
    }

    public JScrollPane getPropertiesListScrollPane() {
        return propertiesListScrollPane;
    }

    public JLabel getValidatorTypeLabel() {
        return validatorTypeLabel;
    }
    
    public void addProperty(String name, String value) {
        propertiesListModel.insertElementAt(name + " : " + value, propertiesListModel.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validatorSelection = new javax.swing.JComboBox();
        validatorTypeLabel = new javax.swing.JLabel();
        propertiesLabel = new javax.swing.JLabel();
        propertiesListScrollPane = new javax.swing.JScrollPane();
        propertiesList = new javax.swing.JList();
        addPropertyButton = new javax.swing.JButton();
        deletePropertyButton = new javax.swing.JButton();

        validatorSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DictionaryValidator", "Item 2", "Item 3", "Item 4" }));
        validatorSelection.setName("validatorSelection"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(validatorTypeLabel, org.openide.util.NbBundle.getMessage(AddValidatorVisualPanel1.class, "AddReporterVisualPanel1.reporterTypeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(propertiesLabel, org.openide.util.NbBundle.getMessage(AddValidatorVisualPanel1.class, "AddReporterVisualPanel1.propertiesLabel.text")); // NOI18N

        propertiesListModel = new DefaultListModel();
        propertiesList.setModel(propertiesListModel);
        propertiesList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        propertiesList.setVerifyInputWhenFocusTarget(false);
        propertiesList.setVisibleRowCount(30000);
        propertiesListScrollPane.setViewportView(propertiesList);

        org.openide.awt.Mnemonics.setLocalizedText(addPropertyButton, org.openide.util.NbBundle.getMessage(AddValidatorVisualPanel1.class, "AddReporterVisualPanel1.addPropertyButton.text")); // NOI18N
        addPropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPropertyButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(deletePropertyButton, org.openide.util.NbBundle.getMessage(AddValidatorVisualPanel1.class, "AddReporterVisualPanel1.deletePropertyButton.text")); // NOI18N
        deletePropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePropertyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propertiesListScrollPane)
                    .addComponent(propertiesLabel)
                    .addComponent(validatorTypeLabel)
                    .addComponent(validatorSelection, 0, 368, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addPropertyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletePropertyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(validatorTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validatorSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(propertiesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertiesListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPropertyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletePropertyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPropertyButtonActionPerformed
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        JFrame frame = new JFrame();
        frame.setLocationRelativeTo(null);
        AddPropertyDialog dialog = new AddPropertyDialog(frame, true);
        dialog.setLocationRelativeTo(null);
        frame.pack();
        
        dialog.setVisible(true);
        
        if(!dialog.isNameEmptyOrNull() && !dialog.isValueEmptyOrNull()) {
            this.addProperty(dialog.getPropertyNameTextField().getText(), dialog.getPropertyValueTextField().getText());
        }
    }//GEN-LAST:event_addPropertyButtonActionPerformed

    private void deletePropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePropertyButtonActionPerformed
        if (propertiesList.getSelectedIndices().length > 0) {
            int[] elementsToRemove = propertiesList.getSelectedIndices();
            
            for (int i = elementsToRemove.length - 1; i >= 0; i--) {
                propertiesListModel.removeElementAt(elementsToRemove[i]);
            }
        }
    }//GEN-LAST:event_deletePropertyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPropertyButton;
    private javax.swing.JButton deletePropertyButton;
    private javax.swing.JLabel propertiesLabel;
    private javax.swing.JList propertiesList;
    private javax.swing.DefaultListModel propertiesListModel;
    private javax.swing.JScrollPane propertiesListScrollPane;
    private javax.swing.JComboBox validatorSelection;
    private javax.swing.JLabel validatorTypeLabel;
    // End of variables declaration//GEN-END:variables
}
