/*
 * Copyright 2015 Andrej Halaj.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.perfcake.pc4nb.wizards.visuals;

import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import org.perfcake.model.Scenario.Reporting.Reporter;
import org.perfcake.pc4nb.core.model.ReportingModel;
import org.perfcake.pc4nb.ui.AbstractPC4NBVisualPanel;
import org.perfcake.pc4nb.ui.tableModel.ReportersTableModel;
import org.perfcake.pc4nb.ui.actions.AddReporterAction;

public final class ReportingVisualPanel extends AbstractPC4NBVisualPanel {

    public ReportingVisualPanel() {
        initComponents();

        addReporterButton.addActionListener(new AddReporterAction(this));
        deleteReporterButton.addActionListener((ActionEvent e) -> {
            int[] selectedRows = reportersTable.getSelectedRows();
            ReportingModel model = (ReportingModel) getModel();
            
            for (int i = selectedRows.length - 1; i >= 0; i--) {
                Reporter reporter = model.getReporting().getReporter().get(selectedRows[i]);
                model.removeReporter(reporter);
            }
        });
    }

    @Override
    public String getName() {
        return "Reporting";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportingPropertiesTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportersTable = new javax.swing.JTable();
        addReporterButton = new javax.swing.JButton();
        editReporterButton = new javax.swing.JButton();
        deleteReporterButton = new javax.swing.JButton();

        reportingPropertiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(reportingPropertiesTable);

        reportersTableModel = new ReportersTableModel();
        reportersTable.setModel(reportersTableModel);
        jScrollPane2.setViewportView(reportersTable);

        org.openide.awt.Mnemonics.setLocalizedText(addReporterButton, org.openide.util.NbBundle.getMessage(ReportingVisualPanel.class, "ReportingVisualPanel.addReporterButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(editReporterButton, org.openide.util.NbBundle.getMessage(ReportingVisualPanel.class, "ReportingVisualPanel.editReporterButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(deleteReporterButton, org.openide.util.NbBundle.getMessage(ReportingVisualPanel.class, "ReportingVisualPanel.deleteReporterButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addReporterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editReporterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteReporterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(addReporterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editReporterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteReporterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReporterButton;
    private javax.swing.JButton deleteReporterButton;
    private javax.swing.JButton editReporterButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable reportersTable;
    private ReportersTableModel reportersTableModel;
    private javax.swing.JTable reportingPropertiesTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().startsWith("reporting-")) {
            //something something
        }
    }
}
