/*
 * Copyright 2015 Andrej Halaj.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.perfcake.pc4nb.wizards.visuals;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import org.netbeans.api.project.Project;
import org.netbeans.api.project.ProjectUtils;
import org.netbeans.api.project.ui.OpenProjects;

public final class ScenarioVisualPanel extends JPanel {
    private Project[] projects;
    
    public ScenarioVisualPanel() {
        projects = OpenProjects.getDefault().getOpenProjects();
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #7";
    }

    public JTextField getScenarioNameTextField() {
        return scenarioNameTextField;
    }

    public JComboBox getProjectComboBox() {
        return projectComboBox;
    }

    public Project[] getProjects() {
        return projects;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scenarioNameLabel = new javax.swing.JLabel();
        scenarioNameTextField = new javax.swing.JTextField();
        xmlLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        projectComboBox = new javax.swing.JComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(scenarioNameLabel, org.openide.util.NbBundle.getMessage(ScenarioVisualPanel.class, "ScenarioVisualPanel.scenarioNameLabel.text")); // NOI18N

        scenarioNameTextField.setText(org.openide.util.NbBundle.getMessage(ScenarioVisualPanel.class, "ScenarioVisualPanel.scenarioNameTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(xmlLabel, org.openide.util.NbBundle.getMessage(ScenarioVisualPanel.class, "ScenarioVisualPanel.xmlLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ScenarioVisualPanel.class, "ScenarioVisualPanel.jLabel1.text")); // NOI18N

        projectNames = new String[projects.length];
        projectComboBoxModel = new DefaultComboBoxModel();

        for (int i = 0; i < projects.length; i++) {
            projectNames[i] = projects[i].getProjectDirectory().getName();
            JLabel newMenuItem = new JLabel();
            newMenuItem.setHorizontalTextPosition(SwingConstants.LEADING);
            newMenuItem.setAlignmentX(SwingConstants.RIGHT);
            newMenuItem.setIcon(ProjectUtils.getInformation(projects[i]).getIcon());
            projectComboBoxModel.addElement(newMenuItem);
        }
        projectComboBox.setModel(new DefaultComboBoxModel(projectNames));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(scenarioNameLabel))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scenarioNameTextField)
                    .addComponent(projectComboBox, 0, 240, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xmlLabel)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scenarioNameTextField)
                        .addComponent(xmlLabel))
                    .addComponent(scenarioNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox projectComboBox;
    private String[] projectNames;
    private DefaultComboBoxModel projectComboBoxModel;
    private javax.swing.JLabel scenarioNameLabel;
    private javax.swing.JTextField scenarioNameTextField;
    private javax.swing.JLabel xmlLabel;
    // End of variables declaration//GEN-END:variables
}
